apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: space
  name: space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: space
    spec:
      containers:
        - image: iys-customer-employee-interactions
          name: iys-customer-employee-interactions
          resources: { }
status: { }
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: space
  name: space
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: space
  type: ClusterIP
status:
  loadBalancer: { }
